export const SAVE_TODO_TO_FIREBASE="SAVE_TODO_TO_FIREBASE";
export const GET_TODOS_FROM_FIREBASE="GET_TODOS_FROM_FIREBASE";
export const DELETE_TODO_FROM_FIREBASE ="DELETE_TODO_FROM_FIREBASE";
export const UPDATE_TODO_FROM_FIREBASE="UPDATE_TODO_FROM_FIREBASE";